const spots=[
['Sydney Opera House','sydney','명소',-33.8568,151.2153,'하버를 대표하는 건축물 · 투어/공연 예약 추천'],['Royal Botanic Garden','sydney','자연',-33.8642,151.2166,'오페라하우스와 이어 걷기 좋은 무료 정원'],['The Rocks','sydney','산책',-33.8599,151.2090,'역사적인 골목과 주말 마켓'],['BridgeClimb Sydney','sydney','체험',-33.8523,151.2108,'하버브리지 정상 체험 · 사전 예약 필수'],['Museum of Contemporary Art','sydney','문화',-33.8599,151.2090,'서큘러키 전망이 좋은 현대미술관'],['Bennelong','sydney','맛집',-33.8572,151.2148,'오페라하우스 안의 모던 오스트레일리안'],['Mr. Wong','sydney','맛집',-33.8641,151.2083,'활기찬 광둥식 레스토랑 · 예약 추천'],['Sydney Fish Market','sydney','맛집',-33.8732,151.1927,'해산물과 캐주얼한 점심'],['Spice Alley','sydney','맛집',-33.8846,151.2005,'아시아 길거리 음식 골목'],['Bondi Beach','sydney','자연',-33.8915,151.2767,'대표 해변 · 이른 오전 추천'],['Bondi to Coogee Walk','sydney','산책',-33.8984,151.2830,'약 6km 절벽 해안 산책'],['Sean’s Panorama','sydney','맛집',-33.8894,151.2771,'본다이의 편안한 로컬 다이닝'],['Manly Beach','sydney','자연',-33.7972,151.2883,'페리부터 여행이 되는 북부 해변'],['Taronga Zoo','sydney','체험',-33.8433,151.2411,'하버 전망과 호주 동물'],['Queen Victoria Building','sydney','쇼핑',-33.8718,151.2067,'아름다운 역사 건축과 쇼핑'],['Blue Mountains – Echo Point','sydney','근교',-33.7320,150.3120,'세 자매봉 전망 · 하루 투어'],
['Flinders Street Station','melbourne','명소',-37.8183,144.9671,'멜버른 도심 산책의 시작점'],['Hosier Lane','melbourne','산책',-37.8166,144.9691,'대표적인 스트리트 아트 골목'],['NGV International','melbourne','문화',-37.8226,144.9689,'무료 상설전이 풍성한 미술관'],['State Library Victoria','melbourne','문화',-37.8098,144.9652,'돔형 열람실이 인상적인 도서관'],['Queen Victoria Market','melbourne','맛집',-37.8076,144.9568,'식재료와 간식을 즐기는 시장'],['Higher Ground','melbourne','맛집',-37.8159,144.9530,'높은 천장의 인기 브런치 카페'],['Chin Chin','melbourne','맛집',-37.8157,144.9702,'활기찬 동남아 요리'],['Tipo 00','melbourne','맛집',-37.8135,144.9618,'수제 파스타로 유명한 작은 식당'],['Market Lane Coffee','melbourne','카페',-37.8066,144.9582,'멜버른 스페셜티 커피'],['Lune Croissanterie Fitzroy','melbourne','카페',-37.7980,144.9780,'대표 크루아상 · 이른 방문 추천'],['Fitzroy','melbourne','산책',-37.7984,144.9782,'빈티지 숍·카페·거리 예술'],['Royal Botanic Gardens Victoria','melbourne','자연',-37.8304,144.9796,'도심 속 넓은 정원'],['St Kilda Pier','melbourne','자연',-37.8648,144.9737,'노을 산책과 해변'],['Brighton Bathing Boxes','melbourne','명소',-37.9174,144.9860,'컬러풀한 해변 오두막'],['Great Ocean Road – Twelve Apostles','melbourne','근교',-38.6644,143.1051,'장거리지만 압도적인 해안 절경'],['Phillip Island Penguin Parade','melbourne','근교',-38.5050,145.1475,'해질녘 펭귄 퍼레이드 · 예약 필수']
].map((s,i)=>({id:i,name:s[0],city:s[1],cat:s[2],lat:s[3],lng:s[4],desc:s[5]}));
const categories=['전체','맛집','카페','명소','자연','산책','문화','체험','쇼핑','근교'];let active='전체';
const map=L.map('map',{zoomControl:false}).setView([-35.4,147.5],5);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const icon=L.divIcon({className:'marker-icon',iconSize:[16,16]});const markers=[];
const gm=n=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(n+' Australia')}`;
spots.forEach(s=>{const m=L.marker([s.lat,s.lng],{icon}).bindPopup(`<small>${s.city.toUpperCase()} · ${s.cat}</small><h3>${s.name}</h3><p>${s.desc}</p><a target="_blank" rel="noopener" href="${gm(s.name)}">Google Maps ↗</a>`).addTo(map);markers.push({s,m})});
const filters=document.querySelector('#filters'),list=document.querySelector('#spotList');categories.forEach(c=>{const b=document.createElement('button');b.textContent=c;b.className=c==='전체'?'active':'';b.onclick=()=>{active=c;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderSpots()};filters.append(b)});
function renderSpots(){const shown=spots.filter(s=>active==='전체'||s.cat===active);markers.forEach(({s,m})=>shown.includes(s)?m.addTo(map):m.remove());list.innerHTML=shown.map(s=>`<div class="spot" data-id="${s.id}"><small>${s.city.toUpperCase()} · ${s.cat}</small><h3>${s.name}</h3><p>${s.desc}</p><a target="_blank" rel="noopener" href="${gm(s.name)}">GOOGLE MAPS ↗</a></div>`).join('');document.querySelector('#spotCount').textContent=shown.length;list.querySelectorAll('.spot').forEach(el=>el.onclick=e=>{if(e.target.tagName==='A')return;const {m}=markers.find(x=>x.s.id==el.dataset.id);map.setView(m.getLatLng(),14);m.openPopup()})}renderSpots();
const routes={sydney:[
['11.29','도착 & 하버 첫인상',['호텔 체크인','서큘러키','오페라하우스 야경'],'비행 피로를 고려한 가벼운 도보 일정'],['11.30','하버 클래식',['Royal Botanic Garden','Opera House 투어','The Rocks','BridgeClimb 또는 전망대'],'하버 주변을 시계 방향으로 연결'],['12.01','본다이 블루',['Bondi Beach','Bondi–Coogee Walk','Sean’s 저녁'],'맑은 날로 날짜 교체 추천'],['12.02','도심 & 미식',['QVB','MCA','Barangaroo','Mr. Wong'],'쇼핑과 미술관을 섞은 실내 대안'],['12.03','블루마운틴',['Katoomba','Echo Point','Scenic World'],'왕복 1일 투어 또는 기차'],['12.04','페리 데이',['Manly Ferry','Manly Beach','Taronga Zoo 중 택1'],'같은 날 둘 다보다 하나에 집중']
],melbourne:[
['12.05','멜버른 이동',['시드니→멜버른','Flinders Street','Hosier Lane','Chin Chin'],'오후 도착 기준 가벼운 CBD 산책'],['12.06','레이노웨이 & 아트',['Higher Ground','State Library','Arcades','NGV'],'무료 트램 구역과 도보 활용'],['12.07','마켓 & 피츠로이',['Queen Victoria Market','Market Lane','Fitzroy','Lune'],'시장 휴무일이면 12/9와 교체'],['12.08','그레이트 오션 로드',['Torquay','Apollo Bay','Twelve Apostles'],'아주 이른 출발 · 긴 이동 대비'],['12.09','가든 & 베이',['Royal Botanic Gardens','Brighton Boxes','St Kilda 노을'],'기차와 트램으로 남쪽 해안 연결'],['12.10','마지막 커피',['CBD 카페','기념품 쇼핑','공항 이동'],'국제선은 여유 있게 공항 이동']
]};
const cards=document.querySelector('#routeCards');function renderRoutes(city){cards.innerHTML=routes[city].map((r,i)=>`<article class="route-card"><div class="day">0${i+1}</div><small>${r[0]}</small><h3>${r[1]}</h3><ul>${r[2].map((x,j)=>`<li><span>${String(j+1).padStart(2,'0')}</span>${x}</li>`).join('')}</ul><p>${r[3]}</p></article>`).join('')}renderRoutes('sydney');document.querySelectorAll('.city-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.city-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderRoutes(b.dataset.city)});
